model:
    arch: fcn8s
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    frac_img: 1.0 # fraction of the labeled train images used
    get_flow: False
    discard_flow_bottom: False
    path: /path/to/cityscapes/
training:
    train_iters: 300000
    batch_size_lbl: 2
    batch_size_flow: 0
    val_interval: 1000
    n_workers: 2
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    frequency_weighting: False
    lr_schedule:
    resume:
    reset_optimizer: False
    logdir: 'f100/fcn8s'
    tasks: ['input', 'output', 'ground_truth', 'flow'] # for visualize.py
